language: node_js

node_js:
- '8'

cache:
  yarn: true

install:
- yarn install

script:
- yarn run build

addons:
  ssh_known_hosts: 115.159.209.131:28330

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- openssl aes-256-cbc -K $encrypted_f812e1a00ef1_key -iv $encrypted_f812e1a00ef1_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 115.159.209.131\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- rsync -avz -e 'ssh -p 28330' dist/* root@115.159.209.131:/www/wwwroot/music.io-code.com
- ssh -f root@115.159.209.131 -p 28330 "chown -R www:www /www/wwwroot/music.io-code.com/*"
- echo -e "\033[32m 已同步到网站 \033[0m"

notifications:
  email: false
